### ISSUE TITLE
Error with CRD schema on kubernetes v1.16

### ISSUE THREAD

**Issue by RaSerge** [FairwindsOps/rbac-manager#94]
We test your solution on our k8s cluster v1.16.2. 
After applying CRD and RBACDefinition (we copy it from example) in rbac-manager we don't seen any problems:
```
time="2019-10-18T18:40:33Z" level=info msg="Watching RBAC Definitions"
time="2019-10-21T18:47:15Z" level=info msg="Reconciling RBACDefinition rbacmanager-all-users"
```
at the same time in logs of kube-apiserver:
```
E1018 18:47:01 1 customresource_handler.go:655] error building openapi models for rbacdefinitions.rbacmanager.reactiveops.io: SchemaError(io.reactiveops.rbacmanager.v1beta1.RBACDefinition.rbacBindings.roleBindings.namespaceSelector.matchExpressions): array should have exactly one sub-item
```
As a result is no new role binding created and no any errors in logs of rbac-manager.

**Comment by rbren** [comment]
[Possibly related](https://github.com/kubernetes/kubernetes/issues/82651), though apparently that bug was fixed in `v1.16.0-rc.2`

**Comment by RaSerge** [comment]
Small clarification. We use kubernetes version v1.16.2
and the problem still persists.
In `rbac-manager` crd "conditions"  i see:
```json
{
                "lastTransitionTime": "2019-10-18T18:14:23Z",
                "message": "spec.validation.openAPIV3Schema.properties[rbacBindings].items.properties[roleBindings].items.properties[namespaceSelector].properties[matchExpressions].items: Required value: must be specified",
                "reason": "Violations",
                "status": "True",
                "type": "NonStructuralSchema"
            },
```

**Comment by RaSerge** [comment]
after upgrade rbac-manager to 0.8.4 everything works as expected.
